### ISSUE TITLE
on clicking on save and continue in pipeline stage tab , this happens

### ISSUE THREAD

**Issue by akshayISTAR** [ISTARSkills/istarissues#481]
org.json.JSONException: JSONObject["jobId"] is not an int.
	at org.json.JSONObject.getInt(JSONObject.java:603)
	at com.istarindia.apps.recruiter.controller.CreateOrUpdateJobWorkflowController.doGet(CreateOrUpdateJobWorkflowController.java:52)
	at com.istarindia.apps.recruiter.controller.CreateOrUpdateJobWorkflowController.doPost(CreateOrUpdateJobWorkflowController.java:123)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

**Comment by akshayISTAR** [comment]
tested ok
